### ISSUE TITLE
TrimSwitchPoints incrementing iterator at the end of the list

### ISSUE THREAD

**Issue by mikispace** [quangounet/TOPP#32]
Hi Cuong,

I think there's a bug [here](https://github.com/quangounet/TOPP/blob/master/src/TOPP.cpp#L409):

```
if(scur>=0) {
    it++; // it may point to the end of the list and cannot be incremented
```
because the iterator can point at the end of the list `switchpointslist` in case it contains a single `SwitchPoint` of type  `SP_SINGULAR`.

A solution can be either to change the `if` condition:

```
if(scur>=0 && it!=switchpointslist.end()) 
```

or to set `scur=-1` before line [398](https://github.com/quangounet/TOPP/blob/master/src/TOPP.cpp#L398)

The same issue may probably happen also at line [358](https://github.com/quangounet/TOPP/blob/master/src/TOPP.cpp#L358)

**Comment by quangounet** [comment]
Fixed via d5fc57dd15978fb96b7dad0f4dd1b74459871db0
Thanks @mikispace !
